-- MySQL Script generated by MySQL Workbench
-- Sun Jun  1 18:35:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tienda_canasta_familiar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda_canasta_familiar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_canasta_familiar` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tienda_canasta_familiar` ;

-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`administrador` (
  `ID_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_administrador`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 131
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`usuario` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `dirección` VARCHAR(255) NOT NULL,
  `teléfono` VARCHAR(15) NULL DEFAULT NULL,
  `tipo` ENUM('cliente', 'administrador', 'repartidor') NOT NULL,
  PRIMARY KEY (`ID_usuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`carrito` (
  `ID_carrito` INT NOT NULL AUTO_INCREMENT,
  `ID_usuario` INT NULL DEFAULT NULL,
  `fecha_creación` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_carrito`),
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `carrito_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `tienda_canasta_familiar`.`usuario` (`ID_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`categoría`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`categoría` (
  `ID_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`notificación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`notificación` (
  `ID_notificación` INT NOT NULL AUTO_INCREMENT,
  `ID_usuario` INT NULL DEFAULT NULL,
  `mensaje` TEXT NOT NULL,
  `fecha_enviada` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_notificación`),
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `notificación_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `tienda_canasta_familiar`.`usuario` (`ID_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`pago` (
  `ID_pago` INT NOT NULL AUTO_INCREMENT,
  `tipo_pago` ENUM('tarjeta', 'efectivo') NOT NULL,
  `monto_total` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('pendiente', 'confirmado') NOT NULL,
  PRIMARY KEY (`ID_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`repartidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`repartidor` (
  `ID_repartidor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `teléfono` VARCHAR(15) NULL DEFAULT NULL,
  `disponibilidad` ENUM('activo', 'inactivo') NOT NULL,
  PRIMARY KEY (`ID_repartidor`))
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tienda_canasta_familiar`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_canasta_familiar`.`pedido` (
  `ID_pedido` INT NOT NULL AUTO_INCREMENT,
  `ID_usuario` INT NULL DEFAULT NULL,
  `fecha_pedido` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('pendiente', 'en proceso', 'completado') NOT NULL,
  `ID_repartidor` INT NULL DEFAULT NULL,
  `ID_pago` INT NULL DEFAULT NULL,
  `dirección_entrega` VARCHAR(255) NOT NULL,
  `ID_administrador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_pedido`),
  INDEX `ID_usuario` (`ID_usuario` ASC) VISIBLE,
  INDEX `ID_repartidor` (`ID_repartidor` ASC) VISIBLE,
  INDEX `ID_pago` (`ID_pago` ASC) VISIBLE,
  INDEX `ID_administrador` (`ID_administrador` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `tienda_canasta_familiar`.`usuario` (`ID_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `pedido_ibfk_2`
    FOREIGN KEY (`ID_repartidor`)
    REFERENCES `tienda_canasta_familiar`.`repartidor` (`ID_repartidor`)
    ON DELETE SET NULL,
  CONSTRAINT `pedido_ibfk_3`
    FOREIGN KEY (`ID_pago`)
    REFERENCES `tienda_canasta_familiar`.`pago` (`ID_pago`)
    ON DELETE CASCADE,
  CONSTRAINT `pedido_ibfk_4`
    FOREIGN KEY (`ID_administrador`)
    REFERENCES `tienda_canasta_familiar`.`administrador` (`ID_administrador`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
